"""Initial migration

Revision ID: 418153e6ddbf
Revises: 
Create Date: 2025-10-31 19:34:02.185654+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418153e6ddbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('search_limit', sa.Integer(), nullable=False),
    sa.Column('searches_used', sa.Integer(), nullable=False),
    sa.Column('last_reset_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='auth_schema'
    )
    op.create_index(op.f('ix_auth_schema_users_email'), 'users', ['email'], unique=True, schema='auth_schema')
    op.create_index(op.f('ix_auth_schema_users_username'), 'users', ['username'], unique=True, schema='auth_schema')
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='auth_schema'
    )
    op.create_index(op.f('ix_auth_schema_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True, schema='auth_schema')
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['auth_schema.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auth_schema'
    )
    op.create_index(op.f('ix_auth_schema_settings_key'), 'settings', ['key'], unique=True, schema='auth_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.drop_index(op.f('ix_auth_schema_settings_key'), table_name='settings', schema='auth_schema')
    op.drop_table('settings', schema='auth_schema')
    op.drop_index(op.f('ix_auth_schema_refresh_tokens_token'), table_name='refresh_tokens', schema='auth_schema')
    op.drop_table('refresh_tokens', schema='auth_schema')
    op.drop_index(op.f('ix_auth_schema_users_username'), table_name='users', schema='auth_schema')
    op.drop_index(op.f('ix_auth_schema_users_email'), table_name='users', schema='auth_schema')
    op.drop_table('users', schema='auth_schema')
    # ### end Alembic commands ###

